In [1]:
import numpy as np

- Создайте случайную матрицу А1 размерностью 5 на 5
- Транспонируйте матрицу A1
- Найдите обратную матрицу для А1
- Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4
- Создайте нулевую матрицу размерности 3 на 3
- Для всех полученных матриц найдите: определитель, ранг и собственные значения
- Проанализируйте результаты

In [2]:
A1 = np.random.random((5,5))
print(A1)

[[0.5726678  0.16285531 0.09552129 0.65168923 0.05381627]
 [0.02509744 0.11706335 0.3055316  0.38106777 0.77584626]
 [0.07468988 0.41500217 0.95397696 0.24498582 0.22567149]
 [0.36878458 0.73574022 0.50034304 0.71410017 0.54780348]
 [0.82981172 0.71149399 0.52070581 0.34720285 0.52891542]]


In [4]:
print(A1.transpose())

[[0.5726678  0.02509744 0.07468988 0.36878458 0.82981172]
 [0.16285531 0.11706335 0.41500217 0.73574022 0.71149399]
 [0.09552129 0.3055316  0.95397696 0.50034304 0.52070581]
 [0.65168923 0.38106777 0.24498582 0.71410017 0.34720285]
 [0.05381627 0.77584626 0.22567149 0.54780348 0.52891542]]


In [5]:
from numpy import linalg as ln
A_inv = ln.inv(A1)
print(A_inv)

[[ 0.81083128  0.07188651 -0.07469614 -1.36337282  1.25598225]
 [-1.38503655 -1.2911216  -0.61572283  2.10932329  0.11288348]
 [ 0.3671695   0.20839939  1.42494318 -0.95228958  0.03526636]
 [ 1.15808055  0.11816833  0.05118953  0.8361072  -1.17897582]
 [-0.53064871  1.34129166 -0.49097173 -0.30981168  0.50752095]]


In [13]:
A_inv @ A1 # algorithm is broken :(

array([[ 1.00000000e+00,  7.03348874e-17,  3.63867878e-17,
         1.56448321e-16,  3.42203419e-17],
       [-1.55369293e-16,  1.00000000e+00, -2.21360538e-16,
        -1.99778816e-16, -2.23991978e-16],
       [-1.72341860e-17,  6.49985537e-17,  1.00000000e+00,
        -1.04648999e-17,  7.07849921e-17],
       [ 5.79566993e-17,  3.05260038e-17,  8.07241092e-18,
         1.00000000e+00, -7.29446989e-17],
       [ 1.69933892e-17,  1.95649789e-17,  4.71017527e-17,
        -4.68059678e-17,  1.00000000e+00]])

In [14]:
I = np.eye(4) 
A2 = np.random.random((4,4))
A3 = I * A2
print(A3)

[[0.14020189 0.         0.         0.        ]
 [0.         0.14734998 0.         0.        ]
 [0.         0.         0.15573018 0.        ]
 [0.         0.         0.         0.14007731]]


In [15]:
A4 = np.zeros((3,3))
print(A4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(f"Определитель случайной матрицы: \t\t{ln.det(A1):.5f}")
print(f"Определитель транспонированной матрицы: \t{ln.det(A1.transpose()):.5f}")
print(f"Определитель обратной матрицы: \t\t{ln.det(A_inv):.5f}")
print(f"Определитель диагональной матрицы: \t\t {ln.det(A3):.5f}")
print(f"Определитель нулевой матрицы: \t\t {ln.det(A4)}")

Определитель случайной матрицы: 		-0.14695
Определитель транспонированной матрицы: 	-0.14695
Определитель обратной матрицы: 		-6.80498
Определитель диагональной матрицы: 		 0.00045
Определитель нулевой матрицы: 		 0.0


In [17]:
1 / (-0.14695)

-6.805035726437564

In [18]:
print(f"Ранг случайной матрицы: \t\t{ln.matrix_rank(A1)}")
print(f"Ранг транспонированной матрицы: \t{ln.matrix_rank(A1.transpose())}")
print(f"Ранг обратной матрицы: \t\t{ln.matrix_rank(A_inv)}")
print(f"Ранг диагональной матрицы: \t\t{ln.matrix_rank(A3)}")
print(f"Ранг нулевой матрицы: \t\t{ln.matrix_rank(A4)}")

Ранг случайной матрицы: 		5
Ранг транспонированной матрицы: 	5
Ранг обратной матрицы: 		5
Ранг диагональной матрицы: 		4
Ранг нулевой матрицы: 		0


In [19]:
print(f"Собственные значения случайной матрицы: \n{ln.eigvals(A1)}")
print(f"Собственные значения транспонированной матрицы: \n{ln.eigvals(A1.transpose())}")
print(f"Собственные значения обратной матрицы: \n{ln.eigvals(A_inv)}")
print(f"Собственные значения диагональной матрицы: \n{ln.eigvals(A3)}")
print(f"Собственные значения нулевой матрицы: \n{ln.eigvals(A4)}")

Собственные значения случайной матрицы: 
[ 2.19230527+0.j         -0.49350436+0.j          0.23253374+0.36582702j
  0.23253374-0.36582702j  0.72285531+0.j        ]
Собственные значения транспонированной матрицы: 
[ 2.19230527+0.j          0.72285531+0.j          0.23253374+0.36582702j
  0.23253374-0.36582702j -0.49350436+0.j        ]
Собственные значения обратной матрицы: 
[-2.02632453+0.j          1.237531  +1.94691002j  1.237531  -1.94691002j
  1.38340271+0.j          0.45614086+0.j        ]
Собственные значения диагональной матрицы: 
[0.14020189 0.14734998 0.15573018 0.14007731]
Собственные значения нулевой матрицы: 
[0. 0. 0.]
